#!/usr/bin/env python3
"""
PR-III v08c: Running-Continuity Audit

Step 09C verifies that locked sector ledgers connect continuously across the
PR-III electromagnetic, electroweak, neutrino, strong, and anomaly branches. It
adds no correction and introduces no new diagnostic reference.

Reproducibility note:
Continuity checks compare decimal strings generated by different upstream steps.
When those strings represent the same derived quantity but carry different tail
precision, continuity is checked with stored-precision tolerances rather than
byte-exact Decimal equality.
"""

from __future__ import annotations

import json
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Any

getcontext().prec = 90

REPO_ROOT = Path(__file__).resolve().parents[1]
GLOBAL_PATH = REPO_ROOT / "data" / "global_running_anomaly_ledger_seed.json"
ANOMALY_PATH = REPO_ROOT / "data" / "global_anomaly_registry_audit.json"
EW_C1_PATH = REPO_ROOT / "data" / "electroweak_running_candidate_C1.json"
EW_C3_PATH = REPO_ROOT / "data" / "electroweak_neutral_D3_candidate_C3.json"
NU_KERNEL_PATH = REPO_ROOT / "data" / "neutrino_radiative_kernel_seed.json"
NU_FINAL_PATH = REPO_ROOT / "data" / "neutrino_final_closure_audit.json"
STRONG_THRESHOLD_PATH = REPO_ROOT / "data" / "strong_threshold_active_flavor_audit.json"

DECIMAL_STORED_PRECISION_TOL = Decimal("1e-75")


class RunningContinuityAuditError(RuntimeError):
    """Raised when Step 09C continuity audit fails."""


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise RunningContinuityAuditError(f"Missing JSON file: {path}")
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def dec(value: Any) -> Decimal:
    return Decimal(str(value))


def assert_close(label: str, lhs: Decimal, rhs: Decimal, tol: Decimal = DECIMAL_STORED_PRECISION_TOL) -> Decimal:
    """Return lhs-rhs if two stored-decimal values agree within repository precision."""
    diff = lhs - rhs
    if abs(diff) > tol:
        raise RunningContinuityAuditError(f"{label} mismatch: diff={diff} exceeds tolerance={tol}")
    return diff


def build_running_continuity_audit() -> dict[str, Any]:
    global_ledger = load_json(GLOBAL_PATH)
    anomaly = load_json(ANOMALY_PATH)
    ew_c1 = load_json(EW_C1_PATH)
    ew_c3 = load_json(EW_C3_PATH)
    nu_kernel = load_json(NU_KERNEL_PATH)
    nu_final = load_json(NU_FINAL_PATH)
    strong_threshold = load_json(STRONG_THRESHOLD_PATH)

    if global_ledger.get("status") != "STEP_09A_GLOBAL_LEDGER_LOCKED":
        raise RunningContinuityAuditError("Step 09A global ledger must be locked before Step 09C.")
    if anomaly.get("status") != "STEP_09B_ANOMALY_REGISTRY_AUDIT_LOCKED":
        raise RunningContinuityAuditError("Step 09B anomaly registry must be locked before Step 09C.")
    if ew_c1.get("status") != "STEP_06C_EW_RUNNING_CANDIDATE_GENERATED":
        raise RunningContinuityAuditError("Step 06C electroweak transport must exist before Step 09C.")
    if ew_c3.get("status") != "STEP_06J_NEUTRAL_D3_REFINEMENT_GENERATED":
        raise RunningContinuityAuditError("Step 06J electroweak closure must exist before Step 09C.")
    if nu_final.get("status") != "STEP_07F_FINAL_NEUTRINO_CLOSURE_AUDIT_LOCKED":
        raise RunningContinuityAuditError("Step 07F neutrino closure must be locked before Step 09C.")
    if strong_threshold.get("status") != "STEP_08D_THRESHOLD_ACTIVE_FLAVOR_AUDIT_LOCKED":
        raise RunningContinuityAuditError("Step 08D threshold ledger must be locked before Step 09C.")

    alpha0 = dec(ew_c1["frozen_inputs"]["alpha_PR_0_inv"])
    delta_run = dec(ew_c1["derived_transport"]["Delta_run_C1_PR"])
    alpha_mu = dec(ew_c1["derived_transport"]["alpha_PR_C1_inv_muEW"])
    assert_close("alpha transport identity", alpha0 - delta_run, alpha_mu)
    if alpha_mu >= alpha0:
        raise RunningContinuityAuditError("Alpha inverse did not lower under EW transport.")

    pi_w = dec(ew_c3["derived_D3"]["Pi_W_C3_PR"])
    pi_z = dec(ew_c3["derived_D3"]["Pi_Z_C3_PR"])
    if Decimal(1) + pi_w <= 0 or Decimal(1) + pi_z <= 0:
        raise RunningContinuityAuditError("Electroweak C3 mass factors must be positive.")

    eps_ew = dec(ew_c3["frozen_inputs"]["epsilon_V_PR"])
    eps_nu = dec(nu_kernel["electroweak_stability_scale"]["epsilon_nu_PR"])
    assert_close("neutrino/EW epsilon bridge", eps_nu, eps_ew)

    lambda_ew = dec(str(strong_threshold["electroweak_matching_scale_audit"]["Lambda_EW_PR_GeV"]))
    top = dec(str(strong_threshold["electroweak_matching_scale_audit"]["top_threshold_GeV"]))
    if lambda_ew <= top:
        raise RunningContinuityAuditError("Strong threshold continuity failed at Lambda_EW_PR.")
    if int(strong_threshold["electroweak_matching_scale_audit"]["n_f_PR_at_Lambda_EW_PR"]) != 6:
        raise RunningContinuityAuditError("n_f at Lambda_EW_PR must be 6.")

    anomaly_gates = anomaly.get("acceptance_gates", {})
    required_anomaly = [
        "hypercharge_convention_fixed",
        "SU3_cubed_anomaly_cancels",
        "SU3_squared_U1_anomaly_cancels",
        "SU2_squared_U1_anomaly_cancels",
        "U1_cubed_anomaly_cancels",
        "gravity_squared_U1_anomaly_cancels",
        "Witten_anomaly_absent",
        "residual_U1em_vectorlike",
        "external_anomaly_canceling_fields_not_inserted",
    ]
    failed_anomaly = [gate for gate in required_anomaly if anomaly_gates.get(gate) is not True]
    if failed_anomaly:
        raise RunningContinuityAuditError(f"Anomaly continuity failed: {failed_anomaly}")

    return {
        "project": "Projection Relativity III",
        "dataset": "global_running_continuity_audit",
        "status": "STEP_09C_RUNNING_CONTINUITY_AUDIT_LOCKED",
        "input_policy": {
            "uses_only_locked_PR_outputs": True,
            "new_diagnostic_references_introduced": False,
            "generation_values_modified": False,
            "new_corrections_computed": False,
        },
        "continuity_tests": {
            "em_to_ew_alpha_transport": {
                "alpha_PR_inv_0": str(alpha0),
                "Delta_run_C1_PR": str(delta_run),
                "alpha_PR_C1_inv_muEW": str(alpha_mu),
                "inverse_alpha_lowered": True,
                "status": "PASS",
            },
            "ew_transport_to_weak_mass_ledger": {
                "Pi_W_C3_PR": str(pi_w),
                "Pi_Z_C3_PR": str(pi_z),
                "one_plus_Pi_W_positive": True,
                "one_plus_Pi_Z_positive": True,
                "MW_PR_GeV": ew_c3["corrected_weak_ledger_C3"]["MW_C3_PR_GeV"],
                "MZ_PR_GeV": ew_c3["corrected_weak_ledger_C3"]["MZ_C3_PR_GeV"],
                "GF_PR_GeV_minus2": ew_c3["corrected_weak_ledger_C3"]["GF_PR_GeV_minus2"],
                "status": "PASS",
            },
            "ew_to_neutrino_stability": {
                "epsilon_nu_PR": str(eps_nu),
                "epsilon_shared_with_weak_vector_factor": True,
                "m1_branch_status": "protected_at_multiplicative_order",
                "normal_ordering_status": "stable",
                "m_beta_beta_meV": nu_final["final_PR_branch"]["m_beta_beta_meV"],
                "status": "PASS",
            },
            "ew_scale_to_strong_threshold_ledger": {
                "Lambda_EW_PR_GeV": str(lambda_ew),
                "top_threshold_PR_GeV": str(top),
                "Lambda_EW_above_top_threshold": True,
                "n_f_PR_at_Lambda_EW_PR": "6",
                "beta0_PR_at_Lambda_EW_PR": strong_threshold["electroweak_matching_scale_audit"]["beta0_PR_at_Lambda_EW_PR"],
                "status": "PASS",
            },
            "anomaly_continuity": {
                "local_gauge_anomalies": "cancel_per_generation",
                "Witten_anomaly": "absent",
                "residual_U1em": "vectorlike",
                "external_fields_inserted": False,
                "status": "PASS",
            },
        },
        "acceptance_gates": {
            "alpha_connects_to_EW_transport": True,
            "EW_transport_connects_to_final_weak_mass_ledger": True,
            "neutrino_kernel_uses_EW_boundary_scale": True,
            "strong_threshold_ledger_continuous_at_Lambda_EW": True,
            "anomaly_registry_compatible_with_continuity_chain": True,
            "no_new_diagnostic_reference_introduced": True,
            "no_generated_sector_value_modified": True,
            "step_09D_defined": True,
        },
        "next_step": "Step 09D: no-fit provenance manifest",
    }


def main() -> None:
    print(json.dumps(build_running_continuity_audit(), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
